name: Test for lake_package_exists

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  current-dir:
    name: lake_package_directoryの入力欄を空にした場合のテスト
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Run Action
        uses: ./
        id: test-step

      - name: assert output
        if: steps.test-step.outputs.lake_package_exists != 'true'
        run: exit 1

  nolean:
    name: Test配下のlakeパッケージでないディレクトリを指定した場合のテスト
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Run Action
        uses: ./
        id: test-step
        with:
          lake_package_directory: './Test/NoLean'
        continue-on-error: true

      - name: assert output
        if: steps.test-step.outputs.lake_package_exists != 'false'
        run: exit 1

  plain:
    name: Test配下のlakeパッケージを指定した場合のテスト
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Run Action
        uses: ./
        id: test-step
        with:
          lake_package_directory: './Test/Plain'

      - name: assert output
        if: steps.test-step.outputs.lake_package_exists != 'true'
        run: exit 1